set(SRC_FILES
    App.cpp
    AppUtil.cpp
    Actor.cpp
    Entity.cpp
    AllObjects.cpp
    Background.cpp
    MapBlock.cpp
    FloorMap.cpp
    NumericDisplayText.cpp
    Player.cpp
    Stair.cpp
    Shop.cpp
    Item.cpp
    Door.cpp
    Enemy.cpp
    NPC.cpp
    DynamicReplacementComponent.cpp
    StatusUI.cpp
    MenuUI.cpp
    DialogueManager.cpp
    ScriptEngine.cpp
    Trigger.cpp
)

set(INCLUDE_FILES
    App.hpp
    AppUtil.hpp
    Actor.hpp
    Entity.hpp
    AllObjects.hpp
    Background.hpp
    MapBlock.hpp
    FloorMap.hpp
    NumericDisplayText.hpp
    Player.hpp
    Stair.hpp
    Shop.hpp
    Item.hpp
    Door.hpp
    Enemy.hpp
    NPC.hpp
    DynamicReplacementComponent.hpp
    StatusUI.hpp
    MenuUI.hpp
    DialogueManager.hpp
    ScriptEngine.hpp
    Trigger.hpp
)

set(TEST_FILES
)
