set(SRC_FILES
    App.cpp
    AppUtil.cpp
    Entity.cpp
    AllObjects.cpp
    Tile.cpp
    StaticTile.cpp
    EventTile.cpp
    CollectableTile.cpp
    Background.cpp
    MapBlock.cpp
    FloorMap.cpp
    NumericDisplayText.cpp
    Player.cpp
    Stair.cpp
    Shop.cpp
    Item.cpp
    Door.cpp
    Enemy.cpp
    NPC.cpp
)

set(INCLUDE_FILES
    App.hpp
    AppUtil.hpp
    Entity.hpp
    AllObjects.hpp
    Tile.hpp
    StaticTile.hpp
    EventTile.hpp
    CollectableTile.hpp
    Background.hpp
    MapBlock.hpp
    FloorMap.hpp
    NumericDisplayText.hpp
    Player.hpp
    Stair.hpp
    Shop.hpp
    Item.hpp
    Door.hpp
    Enemy.hpp
    NPC.hpp
)

set(TEST_FILES
)
